spring:
  config:
    import:
      - optional:classpath:secret/notion.yml
      - optional:classpath:secret/discord.yml
  application:
    name: error
logging:
  level:
    root: info
    com.gitbaby: debug